### ISSUE TITLE
Remapping of frames not working?

### ISSUE THREAD

**Issue by skasperski** [rock-core/drivers-transformer#9]
I always thought, remapping of frame names is done in the transformer configuration script "transforms.rb", but in my current setup I have this line in the config:

```
dynamic_transform "odo.odometry_samples", "robot" => "odometry"
```

But whatever other names I give to "Body" or "odometry" (which are set like this in the RigidBodyState's source_frame and target_frame fields), will cause this transform to be ignored. I receive only this warning:

```
Vizkit[WARN]: /odo.odometry_samples produced a transformation for
Vizkit[WARN]:     Body => odometry,
Vizkit[WARN]:     but I was expecting robot => odometry
Vizkit[WARN]:   I am ignoring this transformation. You will get this message only once,
Vizkit[WARN]:   but get a notification if the right transformation is received later.
```

**Comment by doudou** [comment]
The component itself (here /odo) needs to be configured so that it produces the expected transformation. There are usually XXX_frame properties for this purpose.

Syskit does fully automated configuration (i.e. you don't have to touch the component's configuration(s)), but that requires quite a bit more modelling.
